spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  application:
    name: huy-shop
  data:
    rest:
      base-path: /api



  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/HuyShop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

server:
  port: 8088

#eureka:
#  client:
#    service-url:
#      default-zone: 'http://localhost:8761/eureka'