spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  data:
    rest:
      base-path: /api



  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/HuyShop
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
